[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

# SPA routing - redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"