[build]
  publish = "."

# API routes - handle functions first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Auth callback - serve the callback page directly
[[redirects]]
  from = "/auth/callback/"
  to = "/auth/callback/index.html"
  status = 200

# SPA routing - redirect all other routes to index.html (but exclude auth callback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"